### PR TITLE
Issue 51 Adding contributors to site with links to profile 

### PR DESCRIPTION
**Pull request by SWELLZ**
This is in regard to issue #51 to add contributors to the site. It is a flex box so it will be mobile responsive by default.

As far as I know, there's no way to automatically do it but these images are lazy loaded so it will be more efficient! I would love to be added to the contributors for this repo!!

### CODE REVIEW

**Comment by AmanSarraf** [comment]
hey @SWELLZ , can you adjust the css a bit the current build doesn't looks good https://i.imgur.com/MVsFMFe.png

**Comment by SWELLZ** [comment]
@AmanSarraf sorry I don't have those pink cards on my end. Do you prefer the look of the pink cards?

**Comment by AmanSarraf** [comment]
@SWELLZ  you can remove the pink one and rearrange your style with bit of css so as they could look better.

**Comment by SWELLZ** [comment]
@AmanSarraf no worries, my recent commits re-style the cards to better fit the site with the pink. Let me know what you think!

**Comment by AmanSarraf** [comment]
Thanks @SWELLZ , looks good , can you remove the repeated entries https://i.imgur.com/DMJHqgn.png

**Comment by SWELLZ** [comment]
Hi @AmanSarraf on my end there are no extra items https://imgur.com/a/xDzE9HF

**Comment by SWELLZ** [comment]
Make sure you're on the master branch cause there are no items in the contributors section on that branch. And on my branch, there are no extras. Im not exactly sure why that's happening then

**Pull request merged**
