### PR TITLE
made some changes in headline 

### PR DESCRIPTION
**Pull request by Shobhnik13**

### CODE REVIEW

**Comment by AmanSarraf** [comment]
LGTM,
good work @Shobhnik13 , I shall merge this PR.
also you don't need to close a PR for any update, you can simply commit to the open PR. also mention the respective issue number as well , that will helpful in tracking the issue is resolved or not.
Fixes #70

**Comment by Shobhnik13** [comment]
Thanks Aman for guiding me I will definitely keep these suggestions in mind while contributing further

**Comment by AmanSarraf** [comment]
we have some conflicts here @Shobhnik13 , I am facing problem resolving from my end , would you close and and commit the changes again after the master.

**Comment by Shobhnik13** [comment]
Sure

**Pull request closed without merging**
