### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by cleverhare**

### CODE REVIEW

**Review by AmanSarraf — COMMENTED** [review]
Nice work @cleverhare , Lets's add the contributors badge in the README as well

**Comment by cleverhare** [comment]
Okay bro. I have added mines and yours others need to add and then generate PR accordingly

**Comment by cleverhare** [comment]
And I guess it can be accepted now

**Comment by AmanSarraf** [comment]
Fixes https://github.com/AmanSarraf/Opensource-Buddy/issues/3

**Pull request merged**
